const glob = require('glob');
const path = require('path');

// 获取 docs 目录下的第一层目录
const docDirs = glob.sync('docs/*', { onlyDirectories: true }).map(dir => path.basename(dir));

// 去除目录名称中的数字编号
const formatDirName = (dir) =>   dir.replace(/^\d+-/, '') ;

const sidebars = {};

docDirs.forEach(dir => {
  sidebars[formatDirName(dir)] = [{ type: 'autogenerated', dirName: dir }];
});

module.exports = sidebars;